back_levels:
    resource: "@BackBundle/Controller/LevelsController.php"
    type:     annotation

back_competions:
    resource: "@BackBundle/Controller/CompetionsController.php"
    type:     annotation

back_posts:
    resource: "@BackBundle/Controller/PostsController.php"
    type:     annotation
    
frontend:
    resource: "@FrontBundle/Controller/DefaultController.php"
    type:     annotation    

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    
