<?php

namespace BackBundle\Repository;

/**
 * CompetionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetionsRepository extends \Doctrine\ORM\EntityRepository
{
}
