<?php

namespace BackBundle\Repository;

/**
 * LevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelsRepository extends \Doctrine\ORM\EntityRepository
{
}
