<?php

namespace BackBundle\Repository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{
    public function inIndex() {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u')->orderBy('u.createdAt', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
