<?php

namespace FrontBundle\Repository;

/**
 * LanguesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguesRepository extends \Doctrine\ORM\EntityRepository
{
}
