<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwosvno\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwosvno/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWwosvno.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWwosvno\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWwosvno\appDevDebugProjectContainer([
    'container.build_hash' => 'Wwosvno',
    'container.build_id' => '185368b2',
    'container.build_time' => 1565613197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwosvno');
