<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO3rxnfz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO3rxnfz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO3rxnfz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO3rxnfz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerO3rxnfz\appDevDebugProjectContainer([
    'container.build_hash' => 'O3rxnfz',
    'container.build_id' => '7926d0e4',
    'container.build_time' => 1565606037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO3rxnfz');
